name: 🐞 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
assignees:
  - slydlake
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the fields below as completely as possible.

  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the issue is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How to reproduce the issue
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant version
      placeholder: "e.g. 2024.12.0"
    validations:
      required: false

  - type: input
    id: integration-version
    attributes:
      label: openmediavault integration version
      placeholder: "e.g. v1.0.0"
    validations:
      required: false

  - type: input
    id: omv-version
    attributes:
      label: openmediavault software version
      placeholder: "e.g. 7.3.0"
    validations:
      required: true

  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostics data
      description: If you are seeing incorrect data through the integration, please paste integration diagnostics data here.
      render: json
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Traceback / Error logs
      description: If you come across any trace or error logs, please provide them.
      render: text
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
